# Generated by Django 6.0.4 on 2026-04-11 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapasapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tapasapp.account'),
            preserve_default=False,
        ),
    ]
